# Generated by Django 5.2.5 on 2025-11-27 12:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=128)),
                ('shedule', models.DateTimeField()),
                ('country', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('abbreviation', models.CharField(max_length=32)),
                ('info', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_usdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difficulty_rate', models.CharField(choices=[('super easy', 'even kids can make'), ('easy', 'everyone can repeat'), ('normal', 'skilled'), ('hard', 'nice cooker'), ('pro', 'growing talent'), ('chef', 'cooking artist')], max_length=64)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('average_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventions', to=settings.AUTH_USER_MODEL)),
                ('liked_users', models.ManyToManyField(related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
                ('cooking', models.CharField(max_length=256)),
                ('type_of_cuisine', models.CharField(max_length=256)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='receipts.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('category', models.CharField(max_length=128)),
                ('amount', models.IntegerField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='amount_value_check')],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categories', models.ManyToManyField(related_name='ingredient', to='receipts.ingredientcategory')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.ingredient')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receipts.measure')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ManyToManyField(related_name='receipt', to='receipts.equipment')),
                ('ingredients', models.ManyToManyField(related_name='receipt', through='receipts.IngredientsAmount', to='receipts.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientsamount',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt'),
        ),
        migrations.AddField(
            model_name='dish',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='receipts.receipt'),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('content', models.TextField()),
                ('template', models.ImageField(blank=True, null=True, upload_to='')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='receipts.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('institution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipts.institution')),
                ('menu', models.ManyToManyField(related_name='restaurants', to='receipts.dish')),
            ],
            bases=('receipts.institution',),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('institution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipts.institution')),
                ('assorti', models.ManyToManyField(related_name='shops', to='receipts.ingredient')),
            ],
            bases=('receipts.institution',),
        ),
    ]
