# Generated by Django 5.2.5 on 2025-12-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='receipts.dish'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.post'),
        ),
    ]
